Guests = ['Jack Sparrow', 'Cristiano Ronaldo', 'Lionel Messi', 'Mo Salah']
print(f'Hey {Guests[0]}, Would you like to come to my party?')
print(f'Hey {Guests[1]}, Would you like to come to my party?')
print(f'Hey {Guests[2]}, Would you like to come to my party?')
print(f'Hey {Guests[3]}, Would you like to come to my party?')
wont_come = Guests.pop(2)
print(f"Unfortunately {wont_come} Can't Make it")
Guests.insert(2, 'Eden Hazard')
print(f'Hey {Guests[2]}, Would you like to come to my party?')
print("Great news! we found a bigger table")
Guests.insert(0, 'Marmoush')
Guests.insert(2, 'De Paul')
Guests.insert(-1, 'Jim Carrey')
print(f'Hey {Guests[4]}, Would you like to come to my party?')
print(f'Hey {Guests[5]}, Would you like to come to my party?')
print(f'Hey {Guests[6]}, Would you like to come to my party?')
print(len(Guests))
print("Unfortunately the table won't come on time so i have to invite only two people")
print(f"I'm sorry {Guests.pop(0)} i can only invite two people")
print(f"I'm sorry {Guests.pop(1)} i can only invite two people")
print(f"I'm sorry {Guests.pop(2)} i can only invite two people")
print(f"I'm sorry {Guests.pop(3)} i can only invite two people")
print(f"I'm sorry {Guests.pop()} i can only invite two people")
print(Guests)
print(f'Hey {Guests[0]}, Would you like to come to my party?')
print(f'Hey {Guests[1]}, Would you like to come to my party?')
del Guests[0]
del Guests[0]
print(Guests)